name: Python package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run unit tests
        run: uv run scripts/make.py --test

      - name: Check types with mypy
        run: uv run scripts/make.py --mypy

      - name: Check types with pyright
        run: uv run scripts/make.py --pyright

      - name: Lint with ruff
        run: uv run scripts/make.py --ruff
